# Generated by Django 5.2.7 on 2025-11-22 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
