# Generated by Django 5.2.7 on 2025-11-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentplan',
            name='first_due_date',
        ),
        migrations.RemoveField(
            model_name='installmentplan',
            name='installment_amount',
        ),
        migrations.RemoveField(
            model_name='installmentplan',
            name='total_installments',
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
