# Generated by Django 5.2.7 on 2025-11-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchasing_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
